version: "0"

services:

  postgresql:
    image: postgres:latest
    restart: always
    ports: 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank

  keycloak:
    image: bitnami/keycloak:latest
    ports: 8080:8080
    environment:
      KEYCLOAK_BIND_ADDRESS: localhost
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_ENABLE_HTTPS: false
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: user
      KEYCLOAK_ADMIN_PASSWORD: user
    depends_on:
      - postgresql

